version: "3.9"
services:
# APサーバーコンテナの作成
  app:
    build: ./infra/php
    volumes:
      - ./src:/data

# Webサーバーコンテナの作成
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data